base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout"),
    path('register/', views.registerPage, name="register"),
    path('item/', views.item, name="item"),
    path('item/create/', views.create_item, name="item-create"),
    path('item/<str:pk>/', views.item_detail, name="item-detail"),
    path('profile/<str:pk>/', views.user_profile, name="user-profile"),
    path('item/<str:pk>/edit/', views.update_item, name="item-update"),
    path('item/<str:pk>/delete/', views.delete_item, name="item-delete"),
    path('category/', views.category, name="category"),
    path('category/create/', views.create_category, name="category-create"),
    path('category/<str:pk>/update/', views.update_category, name="category-update"),
    path('category/<str:pk>/delete/', views.delete_category, name="category-delete"),
    path('search/', views.search, name="search"),
    path('item/<str:pk>/reuse/', views.reuse_item, name="item-reuse"),
    path('about/', views.about, name="about"),
    path('api/credits/', views.credit_list, name='credit-list'),
    path('api/credits/<str:pk>', views.credit_detail, name='credit-detail'),
    
]

waste/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.urls import reverse


class User(AbstractUser):
    employee_id = models.CharField(max_length=10, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    avatar = models.ImageField(
        upload_to='users/', null=True, blank=True, default="avatar.svg")
    section = models.CharField(max_length=200, null=True, blank=True)
    department = models.CharField(max_length=200, null=True, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=200)
    name_th = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(max_length=200, blank=True, null=True, unique=True)
    parent_category = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.DO_NOTHING)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='categories/',
                              blank=True, null=True, default="no-image.png")

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            return super().save(*args, **kwargs)

    #subcategories = Category.objects.filter(parent_category__id=target_category.id)


class Station(models.Model):
    name = models.CharField(max_length=100)
    location = models.TextField(null=True, blank=True)
    staff = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to='stations/',
                              null=True, blank=True, default="no-image.png")

    def __str__(self):
        return self.name

# Reusable Material


class Item(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, null=True)
    description = models.TextField(null=True, blank=True)
    station = models.ForeignKey(
        Station, on_delete=models.DO_NOTHING, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField(default=1)
    size = models.CharField(max_length=50, null=True, blank=True)
    weight = models.FloatField(blank=True, null=True)
    image = models.ImageField(
        upload_to='items/%Y/%m/%d/', null=True, blank=True)
    reusable = models.BooleanField(default=True)  # Reusable
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return "{}: {}".format(self.id, self.name)

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

    def get_absolute_url(self):
        return reverse("item-detail", args=[self.id])

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.name)
    #         return super().save(*args, **kwargs)


class Reuse(models.Model):
    DRAFT = 'DR'
    PENDING = 'PE'
    DONE = 'DO'
    CANCEL = 'CA'
    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (PENDING, 'Pending'),
        (DONE, 'Done'),
        (CANCEL, 'Cancel'),
    ]
    item = models.ForeignKey(Item, on_delete=models.DO_NOTHING, null=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default=PENDING)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return "{}".format(self.id)


class Credit(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    total_point = models.FloatField(null=True, blank=True, default=0)
    owner_point = models.FloatField(null=True, blank=True, default=0)
    reuse_point = models.FloatField(null=True, blank=True, default=0)
    description = models.CharField(
        max_length=100, null=True, blank=True, default='Koonkah')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True, null=True, blank=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']
        db_table = 'credit'

    def save(self, *args, **kwargs):
        self.owner_point = self.user.item_set.count()
        self.reuse_point = self.user.reuse_set.count()
        self.total_point = self.owner_point + self.reuse_point
        super(Credit, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse
import os
from .models import Category, Item, Reuse, Station, User, Credit
from .forms import ItemForm, ReuseForm, CategoryForm

from .serializers import CreditSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

# Create your views here.


@api_view(['GET'])
def credit_list(request):
    if request.method == 'GET':
        credit = Credit.objects.all()
        serializer = CreditSerializer(credit, many=True)
        return JsonResponse(serializer.data, safe=False)

    # elif request.method == 'POST':
    #     serializer = CreditSerializer(data=request.data)
    #     if serializer.is_valid():
    #         serializer.save()
    #         return JsonResponse(serializer.data, status=status.HTTP_201_CREATED)
    #     return JsonResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def credit_detail(request, pk):
    user = User.objects.get(employee_id=pk)
    try:
        credit = Credit.objects.get(user=user)
    except Credit.DoesNotExist:
        return JsonResponse(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CreditSerializer(credit)
        return JsonResponse(serializer.data)


def home(request):
    items = Item.objects.filter().order_by('-updated', '-created')[0:4]
    context = {'items': items}
    return render(request, 'base/index.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        # try:
        #     user = User.objects.get(username=username)
        #     print(user)
        # except:
        #     messages.error(request, 'Incorrect username or password.')

        if user is not None:
            if user.is_active:
                login(request, user)

                if request.POST.get('remember') == False:
                    request.session.set_expiry(0)
                # print('Already login to ', user)
                return redirect('home')
            else:
                messages.error(
                    request, 'Your account is inactive. Please contact your administrator.')
        else:
            messages.error(request, 'Incorrect username or password.')

    context = {}
    return render(request, 'base/login.html', context)


def logoutPage(request):
    logout(request)
    return redirect('home')


def registerPage(request):

    if request.method == 'POST':
        first_name = request.POST.get('first_name').lower()
        last_name = request.POST.get('last_name').lower()
        username = request.POST.get('username').lower()
        employee_id = request.POST.get('employee_id').upper()
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
            messages.error(
                request, 'Username already exists, please try another one.')

        except User.DoesNotExist:
            user = User.objects.create_user(
                username=username, first_name=first_name, last_name=last_name, employee_id=employee_id, email=email, password=password)
            credit, created = Credit.objects.get_or_create(user=user)
            messages.success(request, 'Registration completed sucessfully!')
            login(request, user)
            return redirect('home')

    context = {}
    return render(request, 'base/register.html', context)


def item(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    print(q)

    items = Item.objects.all()
    category = Category.objects.all()
    category_name = None

    if q != '':
        items = Item.objects.filter(Q(category__slug__exact=q))
        category = Category.objects.get(slug=q)
        category_name = category.name

    context = {'items': items,
               'category_name': category_name, 'category': category}
    return render(request, 'base/item_page.html', context)


def item_detail(request, pk):
    item = Item.objects.get(id=pk)

    try:
        item_reuse = item.reuse_set.order_by('-updated', '-created')[0]
    except IndexError:
        item_reuse = None

    return render(request, 'base/item_detail.html', {'item': item, 'item_reuse': item_reuse})


def category(request):
    categories = Category.objects.exclude(parent_category__isnull=True)
    context = {'categories': categories, }
    return render(request, 'base/category_page.html', context)


@login_required(login_url='login')
def create_category(request):
    form = CategoryForm()

    if not request.user.is_superuser:
        return HttpResponse('Sorry, you are not athorized to CREATE the object.')

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('category')
    return render(request, 'base/category_form.html', {'form': form})


@login_required(login_url='login')
def update_category(request, pk):
    category = Category.objects.get(id=pk)
    form = CategoryForm(instance=category)

    if not request.user.is_superuser:
        return HttpResponse('Sorry, you are not athorized to EDIT the object.')

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            return redirect('category')
    return render(request, 'base/category_form.html', {'form': form})


@login_required(login_url='login')
def delete_category(request, pk):
    category = Category.objects.get(id=pk)

    if not request.user.is_superuser:
        return HttpResponse('Sorry, you are not athorized to DELETE the object.')

    if request.method == 'POST':
        category.delete()

        return redirect('category')
    return render(request, 'base/category_delete.html', {'obj': category})


@login_required(login_url='login')
def create_item(request):
    page = 'create'
    form = ItemForm()
    stations = Station.objects.all()
    categories = Category.objects.exclude(parent_category__isnull=True)

    if request.method == 'POST' and 'image' in request.FILES:
        # print(request.POST)
        # print(request.FILES)
        category = Category.objects.get(
            name=request.POST.get('category').lower())
        station = Station.objects.get(name=request.POST.get('station').lower())
        is_reusable = request.POST.get('reusable')
        is_reusable = True if is_reusable else False
        item = Item.objects.create(
            name=request.POST.get('name'),
            owner=request.user,
            category=category,
            station=station,
            quantity=request.POST.get('quantity'),
            size=request.POST.get('size'),
            weight=request.POST.get('weight'),
            image=request.FILES['image'],
            reusable=is_reusable,
            description=request.POST.get('description'),
        )
        credit, created = Credit.objects.get_or_create(user=request.user)
        credit.owner_point = User.objects.get(
            username=request.user.username).item_set.count()
        credit.save()
        messages.success(request, 'Your object was successfully created.')
        # return HttpResponseRedirect(reverse('item-detail', args=(item.id,)))
        return redirect('item')

    context = {'form': form, 'categories': categories, 'stations': stations}
    return render(request, 'base/item_form.html', context)


@login_required(login_url='login')
def update_item(request, pk):
    item = Item.objects.get(id=pk)
    # form = ItemForm(instance=item)
    stations = Station.objects.all()
    categories = Category.objects.exclude(parent_category__isnull=True)

    if request.user != item.owner:
        return HttpResponse('Sorry, you are not athorized to EDIT the object.')

    if request.method == 'POST':
        print(request.POST)
        print(request.FILES)
        if len(request.FILES) != 0:
            if item.image is not None:
                try:
                    os.remove(item.image.path)
                except:
                    pass
            item.image = request.FILES.get('image')

        item.name = request.POST.get('name')
        item.category = Category.objects.get(
            name=request.POST.get('category').lower())
        item.station = Station.objects.get(
            name=request.POST.get('station').lower())
        item.reusable = True if request.POST.get('reusable') else False
        item.quantity = (request.POST.get('quantity'))
        item.weight = request.POST.get('weight')
        item.size = request.POST.get('size')
        item.description = request.POST.get('description')
        item.save()
        messages.success(request, 'Your object was successfully updated.')
        # return HttpResponseRedirect(reverse('item-detail', args=(item.id,)))
        return redirect('item')

    context = {'categories': categories, 'stations': stations, 'item': item}
    return render(request, 'base/item_form.html', context)


@login_required(login_url='login')
def delete_item(request, pk):
    item = Item.objects.get(id=pk)


base/templates/base/item_detail.html
{% extends 'base/main.html' %} {% block content %}

<div class="container py-5 vh-100">
  <div class="row align-items-center">
    <div class="col-md-6 mb-3 text-center">
      <img
        class="img-fluid"
        src="{{ item.image.url }}"
        alt=""
        style="height: 300px; width: auto"
      />
    </div>
    <div
      class="col-md-6 border border-1 rounded-3 bg-light bg-gradient shadow-sm pt-3"
    >
      <div class="container">
        <div class="row">
          <div class="col mb-2 text-end">
            <a
              href="{% url 'item-update' item.id %}"
              class="btn btn-sm btn-outline-secondary rounded-circle"
              role="button"
              ><i class="fa-solid fa-pen-to-square"></i
            ></a>
            <!-- <a href="{% url 'item-delete' item.id %}" class="btn btn-sm btn-outline-danger rounded-circle" role="button"><i class="fa-solid fa-trash-can"></i></a> -->
            <a
              href=""
              class="btn btn-sm btn-outline-danger rounded-circle"
              role="button"
              data-bs-toggle="modal"
              data-bs-target="#exampleModal"
              ><i class="fa-solid fa-trash-can"></i
            ></a>
            <!-- <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Launch demo modal</button> -->
          </div>
          <div class="row mb-2">
            <div class="col-12">
              <nav
                style="
                  --bs-breadcrumb-divider: url(
                    &#34;data:image/svg + xml,
                    %3Csvgxmlns='http://www.w3.org/2000/svg'width='8'height='8'%3E%3Cpathd='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z'fill='currentColor'/%3E%3C/svg%3E&#34;
                  );
                "
                aria-label="breadcrumb"
              >
                <ol class="breadcrumb">
                  <li class="breadcrumb-item">
                    <a
                      href="{% url 'home' %}"
                      class="text-decoration-none text-dark"
                      >หน้าแรก</a
                    >
                  </li>
                  <li class="breadcrumb-item">
                    <a
                      href="{% url 'category' %}"
                      class="text-decoration-none text-dark"
                      >หมวดหมู่</a
                    >
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">
                    {{ item.category.name_th }}
                  </li>
                </ol>
              </nav>
            </div>
            <div class="col-12">
              <h3 class="fw-bold">{{ item.name|title }}</h3>
            </div>
          </div>
          <div class="row mb-4">
            <div class="col-4">
              <span class="badge rounded-pill bg-secondary me-2"
                >{{ item.category.name_th }}</span
              >
            </div>
            <div class="col-8">
              <small
                >สร้างโดย:
                <span class="text-primary"
                  ><a href="{% url 'user-profile' item.owner.id %}" class=""
                    >@{{ item.owner }}</a
                  ></span
                >, อัพเดทล่าสุด: {{ item.updated | timesince }}</small
              >
            </div>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col-12"><h5>รายละเอียด</h5></div>
          <div class="col-12">{{ item.description }}</div>
        </div>
        <div class="row mb-4">
          <div class="col-4 fw-bold">จำนวน:</div>
          <div class="col">{{ item.quantity }} รายการ</div>
        </div>
        <div class="row mb-4">
          <div class="col-4 fw-bold">ขนาด:</div>
          {% if item.size %}
          <div class="col">{{ item.size}}</div>
          {% else %}
          <div class="col text-muted">N/A</div>
          {% endif %}
        </div>
        <div class="row mb-4">
          <div class="col-4 fw-bold">น้ำหนัก:</div>
          <div class="col">{{ item.weight}} กิโลกรัม</div>
        </div>
        <div class="row mb-4">
          <div class="col-4 fw-bold">สถานะ:</div>
          {% if item_reuse is None %}
          <div class="col text-success fw-bold">พร้อมใช้งาน</div>
          {% else %}
          <!-- <div class="col">Reused by @{{ item_reuse.user }}<span class="text-primary fst-italic ms-2 fw-bold">{{ item_reuse.get_status_display | upper }}</span></div> -->
          <div class="col">
            นำไปใช้โดย @{{ item_reuse.user }}<span
              class="text-primary text-success fst-italic ms-2 fw-bold"
              >REUSED</span
            >
          </div>
          {% endif %}
        </div>
      </div>
      <div class="text-center mb-3 mt-5">
        <a
          href="{% url 'item-reuse' item.id %}"
          class="btn btn btn-success rounded-pill px-4"
          role="button"
          ><i class="fa-solid fa-recycle text-light me-2"></i>REUSE</a
        >
        <!-- <button type="submit" class="btn btn-success rounded-pill px-5" value="Submit"><i class="fa-solid fa-recycle text-light"></i> REUSE</button> -->
      </div>
    </div>
  </div>
</div>

<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Launch demo modal</button> -->

<!-- Modal -->
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <i class="fa-solid fa-trash-can me-2"></i>Delete Confirmation
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <p>คูณต้องการลบรายการ {{ item.name|title }} ใช่ไหรือไม่?</p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'item-delete' item.id %}" method="POST">
          {% csrf_token %}

          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Cancel
          </button>
          <button type="submit" class="btn btn-danger" value="Confirm">
            Delete!
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}


base/templates/base/item_form.html
{% extends 'base/main.html' %} {% block content %} {% load static %}

<section class="bg-light pb-3">
  <div class="container text-start pt-5 px-4">
    <h2>ลงทะเบียนวัสดุ</h2>
  </div>

  <div class="container p-4">
    <form class="row g-3" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="col-12">
        <label for="name" class="form-label">ชื่อวัสดุ</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          {% if item.name %}
          value="{{ item.name }}"
          {% endif %}
          placeholder="ระบุชื่อวัสดุ" required
        />
      </div>
      <div class="col-md-6">
        <label for="category" class="form-label">หมวดหมู่</label>
        <select id="category" name="category" class="form-select" value="{{item.category}}" required>
          {% if not item.category %}
          <option disabled value="NULL" selected>กรุณาเลือกหมวดหมู่ ...</option>
          {% endif %}
            {% for category in categories %}
          <option value="{{ category.name }}" {% if category.name == item.category.name %} selected {% endif %}>{{ category.name_th }}</option>
            {% endfor %}
        </select>
      </div>

      <div class="col-md-6">
        <label for="station" class="form-label">สถานที่จัดเก็บ</label>
        <select id="station" name="station" class="form-select" value="{{item.station}}" required>
          {% if not item.station %}
          <option disabled selected>กรุณาเลือกสถานที่จัดเก็บ ...</option>
          {% endif %}
            {% for station in stations %}
          <option value="{{ station.name }}" {% if station.name == item.station.name %} selected {% endif %}>{{ station.name|title }}</option>
            {% endfor %}
        </select>
      </div>

      <div class="col-md-3">
        <label for="quantity" class="form-label">จำนวน</label>
        <input
          type="number"
          class="form-control"
          id="quantity"
          name="quantity"
          {% if item.quantity %}
          value="{{ item.quantity }}"
          {% endif %}
          placeholder="ระบุจำนวน (รายการ)"
          min="1"
          max="10"
          required
        />
      </div>
      <div class="col-md-3">
        <label for="weight" class="form-label"
          >น้ำหนัก<span class="text-muted"></span>
        </label>
        <input
          type="number"
          class="form-control"
          id="weight"
          name="weight"
          {% if item.weight %}
          value="{{ item.weight }}"
          {% endif %}
          placeholder="ระบุน้ำหนัก (กิโลกรัม)"
          min="0"
          step="0.1" required
        />
      </div>
      <div class="col-md-6">
        <label for="size" class="form-label"
          >ขนาด <span class="text-muted">(ถ้ามี)</span>
        </label>
        <input
          type="text"
          class="form-control"
          id="size"
          name="size"
          {% if item.size %}
          value="{{ item.size }}"
          {% endif %}
          placeholder="ระบุขนาด (มม./ซม./ม.)"
        />
      </div>

      <div class="col-12">
        <label for="id_image" class="form-label">อัพโหลดรูปถ่าย</label>
        <div class="input-group">
          <input
            class="form-control"
            type="file"
            id="image"
            name="image"
            {% if item.image %}
            value="{{ item.image.url }}"
            {% endif %}
            onchange="preview()"
            aria-label="Image upload with two button addons"
          />
          <button
            class="btn btn-outline-secondary"
            type="button"
            id="btn-img-preview"
            onclick="toggleImage()"
          >
            <i class="fa-solid fa-eye"></i>
          </button>
          <button
            class="btn btn-outline-secondary"
            type="button"
            id="btn-img-hidden"
            style="display: none"
            onclick="toggleImage()"
          >
            <i class="fa-solid fa-eye-slash"></i>
          </button>
          <button
            class="btn btn-outline-secondary"
            type="button"
            id="image-upload-remove"
            onclick="clearImage()"
          >
            <i class="fa-solid fa-trash-can"></i>
          </button>
        </div>
        {% if item.image %}

        <a href="{{ item.image.url }}" class="text-primary text-decoration-none fst-italic">{{ item.image.name }}</a>
        
        {% endif %}
      </div>
      <div class="col-12">
        <div class="d-grid justify-content-center">
          <img
            id="frame"
            src="{% if form.instance.image %}{{ item.image.url }}{% elif item.image %}{{ item.image.url }}{% endif %}"
            class="img-thumbnail"
            style="display: none; height: 200px; width: auto"
          />
        </div>
      </div>

      <div class="col-12">
        <div class="form-floating">
          <textarea
            class="form-control"
            placeholder="Description"
            id="description"
            name="description"
            style="height: 100px"
          >{% if item.description %}{{ item.description }}{% endif %}</textarea>
          <label for="description" class="form-label">รายละเอียดเพิ่มเติม (ถ้ามี)</label>
        </div>
      </div>

      <div class="col-12">
        <div class="form-check">
          <input
            class="form-check-input"
            type="checkbox"
            id="reusable"
            name="reusable"
            value="reusable"
            required
          />
          <label class="form-check-label" for="reusable"> วัสดุสามารถนำกลับมาใช้ซ้ำได้ ?</label>
          <p><a href="{% static 'images/steel-standard-dimension.png' %}" class="text-info py-2" target="_blank"><i class="fa-solid fa-file-lines me-2"></i>มาตรฐานวัสดุน้ำกลับมาใช้งานใหมา่ในงาน Kaizen</a></p>
        </div>
      </div>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-outline-secondary me-md-2" role="button">Cancel</a>
        <button type="submit" value="Submit" class="btn btn-secondary">Save</button>
      </div>
    </form>
  </div>
</section>
<script>
  function preview() {
    frame.src = URL.createObjectURL(event.target.files[0]);
  }
  function clearImage() {
    document.getElementById("image").value = null;
    frame.src = "";
  }

  function toggleImage() {
    var img_preview = document.getElementById("frame");
    var btn_img_preview = document.getElementById("btn-img-preview");
    var btn_img_hidden = document.getElementById("btn-img-hidden");
    if (img_preview.style.display === "none") {
      img_preview.style.display = "block";
      btn_img_preview.style.display = "none";
      btn_img_hidden.style.display = "block";
    } else {
      img_preview.style.display = "none";
      btn_img_hidden.style.display = "none";
      btn_img_preview.style.display = "block";
    }
  }

</script>
{% endblock %}